name: 'Set Helm Tags'
description: 'Setting application version tags (e.g. for docker image versions) in (e.g. Helm) configuration files for different deployment phases (e.g. dev/stage/prod).'
inputs:
  app:
    description: 'Application to change all version tags for e.g. application docker imnages in a configuration file (e.g. Helm values files)'
    required: true
  phase:
    description: 'Deployment phase (dev/stage/prod/ignore). In mode single the user is free to use whatever name suits except for ignore.'
    required: true
    default: 'dev'
  prefix:
    description: 'File prefix of configuration file (default: values-)'
    required: true
    default: 'values-'
  tag:
    description: 'Version tag to use'
    required: true
  working-directory:
    description: 'working directory'
    required: false
    default: './'
  mode:
    # Currently, 'cascade' can only handle phases dev/stage/prod excplicitely. Whereas the user is free to use whatever suits as phase name in mode 'single'.
    description: 'Whether to cascade or not. When cascading, prod will be deployed to all three stages, stage to stage and dev, and dev to dev only.'
    required: true
  delimiter:
    description: 'Delimiter as regex between application and version tag. Default :\s (e.g. [app]: [tag]). If you use yaml defaults the delimiter will be \s only.'
    required: true
    default: ": "
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Info: ${{ inputs.mode }}"
        if [[ "${{ inputs.deployment-phase }}" == "ignore" ]]; then
          exit 0
        fi
        if [[ "${{ inputs.mode }}" == "cascade" ]]; then
          if [[ "${{ inputs.deployment-phase }}" =~ ^(dev|stage|prod)$ ]]; then
            sed -i 's/${{ inputs.app }}-tag${{ inputs.delimiter }}.*$/${{ inputs.app }}-tag ${{ inputs.tag }}/g' ${{ inputs.prefix }}dev.yaml
          fi
          if [[ "${{ inputs.deployment-phase }}" =~ ^(stage|prod)$ ]]; then
            sed -i 's/${{ inputs.app }}-tag${{ inputs.delimiter }}.*$/${{ inputs.app }}-tag ${{ inputs.tag }}/g' ${{ inputs.prefix }}stage.yaml
          fi
          if [[ "${{ inputs.deployment-phase }}" == "prod" ]]; then
            sed -i 's/${{ inputs.app }}-tag${{ inputs.delimiter }}.*$/${{ inputs.app }}-tag ${{ inputs.tag }}/g' ${{ inputs.prefix }}prod.yaml
          fi
        else
          sed -i 's/${{ inputs.app }}-tag${{ inputs.delimiter }}.*$/${{ inputs.app }}-tag ${{ inputs.tag }}/g' ${{ inputs.prefix }}${{ inputs.deployment-phase }}.yaml
        fi
