name: 'Set Helm Tags'
description: 'Setting Helm Tags'
inputs:
  app:
    description: 'Application to change the tag'
    required: true
  tgt:
    description: 'Target stage (dev/stage/prod/ignore)'
    required: true
    default: 'dev'
  tag:
    description: 'Tag to use'
    required: true
  dir:
    description: 'working directory'
    required: false
    default: './'
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        if [[ "${{ inputs.tgt }}" == "dev" || "${{ inputs.tgt }}" == "stage" || "${{ inputs.tgt }}" == "prod" ]]; then
          sed -i 's/${{ inputs.app }}-tag\s.*$/${{ inputs.app }}-tag ${{ inputs.tag }}/g' values-dev.yaml
        fi
        if [[ "${{ inputs.tgt }}" == "stage" || "${{ inputs.tgt }}" == "prod" ]]; then
          sed -i 's/${{ inputs.app }}-tag\s.*$/${{ inputs.app }}-tag ${{ inputs.tag }}/g' values-stage.yaml
        fi
        if [[ "${{ inputs.tgt }}" == "prod" ]]; then
          sed -i 's/${{ inputs.app }}-tag\s.*$/${{ inputs.app }}-tag ${{ inputs.tag }}/g' values-prod.yaml
        fi
